#!/usr/bin/env python3
"""
Plot per-dataset and per-model Spearman correlations from the SubROC comparison.

The source summary was generated by experiments/comparison_subroc/score_phi.py
with its default size weight alpha=0.7 and no class-balance weight (beta=0).
Run from any directory:
    python thesis/plots/subroc_rank_correlation_alpha_0p7_beta_0/generate_plot.py
"""
from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[3]
SOURCE = ROOT / "experiments" / "comparison_subroc" / "results" / "phi_on_adapt" / "summary.csv"
OUT_DIR = Path(__file__).resolve().parent
VALUE_COLUMN = "spearman_quality_phi_gew"
MODEL_ORDER = ("lr", "rf", "lgbm", "mlp")
MODEL_LABELS = {
    "lr": "logistische Regression",
    "rf": "Random Forest",
    "lgbm": "LightGBM",
    "mlp": "MLP",
}
DATASET_LABELS = {
    "ACSIncome": "ACS Income",
    "ACSMobility": "ACS Mobility",
    "ACSPublicCoverage": "ACS Public Coverage",
    "ACSTravelTime": "ACS Travel Time",
    "Diabetes130US": "Diabetes 130 US",
    "PhishingWebsites": "Phishing Websites",
    "adult": "Adult",
    "bank-marketing": "Bank marketing",
    "covertype": "Covertype",
    "default-of-credit-card-clients": "Credit default",
    "electricity": "Electricity",
    "mushroom": "Mushroom",
    "road-safety": "Road safety",
}


def load_correlations() -> pd.DataFrame:
    """Load the completed SubROC comparison values required for the heatmap."""
    if not SOURCE.is_file():
        raise FileNotFoundError(f"Benötigte SubROC-Zusammenfassung fehlt: {SOURCE}")
    frame = pd.read_csv(SOURCE)
    required = {"dataset", "model", VALUE_COLUMN}
    missing = required - set(frame.columns)
    if missing:
        raise ValueError(f"{SOURCE} fehlen Spalten: {sorted(missing)}")
    frame = frame.loc[:, ["dataset", "model", "n", VALUE_COLUMN]].copy()
    frame[VALUE_COLUMN] = pd.to_numeric(frame[VALUE_COLUMN], errors="coerce")
    frame = frame[frame["model"].isin(MODEL_ORDER)]
    return frame.sort_values(["dataset", "model"]).reset_index(drop=True)


def plot_heatmap(table: pd.DataFrame, output_path: Path) -> None:
    datasets = sorted(table["dataset"].unique(), key=lambda name: DATASET_LABELS.get(name, name))
    pivot = table.pivot(index="dataset", columns="model", values=VALUE_COLUMN)
    pivot = pivot.reindex(index=datasets, columns=MODEL_ORDER)
    data = pivot.to_numpy(dtype=float)

    fig, ax = plt.subplots(figsize=(9.2, 0.75 + 0.55 * len(pivot)))
    image = ax.imshow(data, cmap="RdBu_r", vmin=-1.0, vmax=1.0, aspect="auto")
    ax.set_xticks(range(len(MODEL_ORDER)))
    ax.set_xticklabels([MODEL_LABELS[model] for model in MODEL_ORDER], fontsize=8)
    ax.set_yticks(range(len(pivot.index)))
    ax.set_yticklabels([DATASET_LABELS.get(name, name) for name in pivot.index], fontsize=9)

    for row in range(data.shape[0]):
        for column in range(data.shape[1]):
            value = data[row, column]
            label = "—" if not np.isfinite(value) else f"{value:.2f}"
            ax.text(column, row, label, ha="center", va="center", fontsize=9)

    fig.colorbar(
        image,
        ax=ax,
        fraction=0.046,
        pad=0.04,
        label=r"Spearman-Rangkorrelation $\rho$",
    )
    ax.set_title(
        r"Rangkorrelation der Subgruppenbewertungen SubMod vs. SubROC "
        r"($\alpha = 0.7$, $\beta = 0$)",
        fontsize=10,
    )
    fig.tight_layout()
    fig.savefig(output_path, dpi=150)
    plt.close(fig)


def main() -> None:
    table = load_correlations()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    csv_path = OUT_DIR / "subroc_rank_correlations.csv"
    png_path = OUT_DIR / "subroc_rank_correlations.png"
    table.to_csv(csv_path, index=False)
    plot_heatmap(table, png_path)
    print(f"{len(table)} Datensatz-Modell-Kombinationen verarbeitet")
    print(f"geschrieben: {csv_path}")
    print(f"geschrieben: {png_path}")


if __name__ == "__main__":
    main()
